# -*- coding: utf-8 -*-
"""Text_Summarization_Tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XSB9kCfJOx9pz9jC1RFa7ExSN7ICVrqN
"""

from transformers import pipeline

# Initialize the summarization pipeline
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

def summarize_text(text):
    # Ensure the text is not too long for the model
    max_chunk_size = 1024  # Adjust based on model limits
    if len(text) > max_chunk_size:
        text = text[:max_chunk_size]  # Truncate the text

    # Generate summary
    summary = summarizer(text, max_length=150, min_length=40, do_sample=False)
    return summary[0]['summary_text']

# Example text to summarize
example_text = """
    For my honors project, I'm planning to tackle the challenge of developing an AI-powered text summarization tool.
    The core objective of this project is to create a sophisticated system that can efficiently condense lengthy texts
    into concise summaries, ensuring that the essential information and key points are retained.
    """

# Generate summary
summary = summarize_text(example_text)
print("Summary:", summary)